### ISSUE TITLE
yarn support?

### ISSUE THREAD

**Issue by gioragutt** [bubblydoo/serverless-externals-plugin#8]
We're using `yarn`, and it looks like the code here only supports `package-lock.json` and not `yarn.lock`.

Is it possible to add support for it?

**Comment by hansottowirtz** [comment]
Thanks for opening this issue! I'm working on a version that uses [arborist](https://github.com/npm/arborist) to determine which files should be included, after which yarn will be supported. However I can only continue working on this in February. In the meanwhile, if you really need this plugin, you can use https://github.com/imsnif/synp and `packagePath`.

**Comment by gioragutt** [comment]
Hey man, thanks for the reply! Eventually I ended up packaging my external package into a layer.

I'm not 100% sure if the plugin would solve my problem, but I'll be happy to check your suggestion, or try the new version once you support yarn.

**Comment by hansottowirtz** [comment]
That's also a great option! I'm also exploring different options to solve this issue, but this plugin is usually the easiest. Did you use any library to create the layer? I'll reach out again here when Yarn support is done.

**Comment by gioragutt** [comment]
Nope didn't use a library.

Added a layer definition to my serverless yaml,

And created a script that creates the layer folder based on the externals of my webpack.config.js.

* get externals from webpack 
* cross with package.json to get versions
* create layer folder
* create package.json inside layer folder
* run `yarn install --no-lockfile`
* delete package.json
* `mv node_modules nodejs`

That runs before `sls package`.

EDIT:

Gist showing the script
https://gist.github.com/gioragutt/1f581e60d73c9da57816b56123fe8ba5

**Comment by a4xrbj1** [comment]
Hi Hans Otto,

I'm too trying to use this plugin in combination with Yarn as I need the `saslprep` package to for MongoDb.

I've followed your readme and have added the following code to the serverless.yml file:

```
externals:
    modules:
      - saslprep
```

I also created a file `node-externals.json` with the content:

`["saslprep", "aws-sdk"]`

However, I still get the warning about the missing `saslprep`:

`WARN	Warning: no saslprep library specified. Passwords will not be sanitized`

I'm a beginner and I'm actually changing code that was implemented by a former employee of mine. So hopefully I have done all correct from my side and it's a problem that needs to be fixed with your plugin. If I have overlooked something or did something wrong I'd thankful if you could point it out to me, in laymen's terms. Thanks in advance!

PS: 

I've added:

`  - serverless-externals-plugin`

to the `plugins:` section of the `serverless.yml` file

**Comment by hansottowirtz** [comment]
Hi Andreas,

Thanks for the question!

What this plugin does is indeed include the listed node_modules in the zip that is uploaded to AWS. So it should indeed include the `saslprep` module folder inside `node_modules/saslprep` of the zip.

However, you're using Yarn, but this plugin requires a `package-lock.json` file to determine the dependencies of the modules. 
(e.g. saslprep requires `sparse-bitfield`, so it will also include `node_modules/sparse-bitfield`). Do you also have a `package-lock.json` in your project? 

If I look up the warning, it seems like it's coming from `mongodb-core`, which is dynamically requiring `saslprep`. Can you confirm that you're not using Rollup or Webpack to bundle anything? How is the `mongodb-core` package included in your Lambda? And what version of `mongodb-core` are you using?

Anyway, using the excerpts you provided should still work, whether anything is bundled or not. Serverless will create a zip before uploading. Can you check the contents of `.serverless/<package>.zip`, and check inside if `node_modules/saslprep` is included?

I'm also seeing another possibility:

The code inside `mongodb-core` looks like this (https://github.com/mongodb-js/mongodb-core/blob/master/lib/auth/scram.js):
```
let saslprep;
try {
  saslprep = require('saslprep');
} catch (e) {
  // don't do anything;
}
```
But it doesn't check if the error is RequireError. So this might throw some other error type. You can try to remove the try-catch block and see what happens. (`const saslprep = require('saslprep')`)

Hopefully this helps!

**Comment by a4xrbj1** [comment]
Thanks for taking the time to answer my question, especially so quickly.

I was able to chat briefly with my former developer who wrote the code and he clarified to me that neither Webpack nor Yarn is used (though there's a Yarn as a leftover in the folder which made me believe we use Yarn).

He wrote to me that we only use npm with serverless to deploy the Lambda functions. I have installed the package directly inside the corresponding lambda function and will hopefully know in 20 minutes if that solves the warning (it's indeed not an error but the warning floods our log files too much).

**Comment by hansottowirtz** [comment]
I see, great, I hope it works! I assume you're just uploading the whole node_modules folder, is that correct?

**Comment by hansottowirtz** [comment]
@a4xrbj1 @gioragutt I completely re-wrote the plugin, it now supports Yarn (it uses Arborist so it just analyzes the `node_modules` folder).
Next to that it also supports individual function packaging.

From testing with internal projects it seems to work much better than the previous version, generating smaller packages (and also node_modules structures that are actually correct).

One caveat is that there's only a Rollup plugin right now.

I published it under the `next` branch: https://github.com/bubblydoo/serverless-externals-plugin/tree/next

You can install it with `npm install serverless-externals-plugin@next`. Feedback would be very welcome!

**Comment by a4xrbj1** [comment]
Thanks Hans-Otto for re-writing the plugin! I have solved this error by importing the library manually in the source code. But it will be much easier for other users in the future with your new version.
